pkg/apps/home/urls.py
from django.urls import path 
from . import views

app_name = "home"

urlpatterns = [
    path("", views.LandingView.as_view(), name="landing_page"),
    path("contact-us/", views.contact_us, name="contact-us"),
]

pkg/apps/notifications/urls.py
from django.urls import path

from . import views

app_name = "notifications"

urlpatterns = [
    path("", views.NotificationView.as_view(), name="all"),
    path("read-all/", views.MarkAllRead.as_view(), name="read_all"),
]

pkg/apps/users/urls.py
from django.urls import path, re_path, include

from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("profile/", views.UserProfileView.as_view(), name="profile"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("activation/<user>/<token>/", views.account_confirmation, name="activation"),
    path("password-reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path("password-reset/<user>/<token>/", views.password_reset_confirm, name="password_reset_confirm"),
    
    ## OTP URLS
    path("generate-otp/", views.GenerateOTP.as_view(), name="generate_OTP"),
    path("validate-otp/", views.ValidateOTP.as_view(), name="validate_OTP"),
    path("disable-otp/", views.disableOTP, name="disable_OTP"),
]

pkg/templates/partials/_footer.html
{% load static %}


  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
      <li class="nav-item"><a href="{% url "finances:pricing" %}" class="nav-link px-2 text-body-secondary">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
    </ul>
    <p class="text-center text-body-secondary">&copy; 2023 Company, Inc</p>
  </footer>

pkg/templates/partials/_header.html
{% load static %}


<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container-fluid mx-2">
        <a class="navbar-brand" href="/">{{ site_name }}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">{{ site_name }}</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3 mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="/#about-us">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'finances:pricing' %}">Pricing</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-person-fill"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>
                            <li><a class="dropdown-item" href="{% url 'notifications:all' %}">Notifications</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Sign Out</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="btn btn-lg btn-light mx-md-2" href="{% url 'users:signup' %}">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>

            </div>
        </div>
    </div>
</nav>

pkg/templates/partials/_messages.html
{% load static %}


{% if messages %}
    {% for message in messages %}
    <div id="messages" class="alert alert-{{ message.tags }} alert-dismissible fade show mt-3 d-flex align-items-center" role="alert">
      {{ message }} 
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
{% endif %}

pkg/templates/partials/_pagination.html
{% load static %}

<nav aria-label="Page navigation example" class="my-4">
  <ul class="pagination justify-content-end">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a>
    </li>
    <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link">Prev</a>
    </li>
    {% endif %}
    <li class="page-item active"><a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
    {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link">Next</a>
    </li>
    {% endif %}
  </ul>
</nav>