pkg/apps/home/urls.py
from django.urls import path 
from . import views

app_name = "home"

urlpatterns = [
    path("", views.LandingView.as_view(), name="landing_page"),
    path("contact-us/", views.contact_us, name="contact-us"),
]

pkg/apps/notifications/urls.py
from django.urls import path

from . import views

app_name = "notifications"

urlpatterns = [
    path("", views.NotificationView.as_view(), name="all"),
    path("read-all/", views.MarkAllRead.as_view(), name="read_all"),
]

pkg/apps/notifications/models.py
import datetime
from typing import Optional

import hashid_field
from django.conf import settings
from django.db import models
from django.utils import timezone

from . import managers


class Notification(models.Model):
    id: str = hashid_field.HashidAutoField(primary_key=True)
    user: settings.AUTH_USER_MODEL = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="notifications")
    type: str = models.CharField(max_length=64)

    created_at: datetime.datetime = models.DateTimeField(auto_now_add=True)
    read_at: Optional[datetime.datetime] = models.DateTimeField(null=True, blank=True)
    
    data: dict = models.JSONField(default=dict)

    objects = managers.NotificationManager()

    def __str__(self) -> str:
        return str(self.id)

    @property
    def is_read(self) -> bool:
        return self.read_at is not None

    @is_read.setter
    def is_read(self, val: bool):
        self.read_at = timezone.now() if val else None
    
    @property
    def message(self):
        return self.data.get("message")
    
    @property
    def title(self):
        return self.data.get("title")
    
    @property
    def url(self):
        return self.data.get("url")

pkg/apps/notifications/forms.py
from django import forms

from . import models


class UpdateNotificationForm(forms.ModelForm):
    
    def update(self, instance: models.Notification):
        is_read = cleaned_data["is_read"]
        if is_read != instance.is_read:
            instance.is_read = is_read
            instance.save(update_fields=["read_at"])
        return instance

    class Meta:
        model = models.Notification
        fields = ("id", "is_read")

pkg/apps/notifications/views.py
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, View

from . import models, services

class NotificationView(LoginRequiredMixin, ListView):
    template_name = 'notifications/notification.html'
    context_object_name = "notifications"
    model = models.Notification
    paginate_by = 15
    
    def get_queryset(self):
        return models.Notification.objects.filter(user=self.request.user)


class MarkAllRead(View):
    def get(self, request, *args, **kwargs):
        services.NotificationService.mark_read_all_user_notifications(request.user)
        return redirect(request.META.get("HTTP_REFERER"))

pkg/apps/notifications/templates/notifications/notification.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="container my-5">
    
    <div class="d-flex justify-content-between align-items-center">
        <h3>Notifications</h3>
        <ul class="nav nav-pills mb-3 d-flex justify-content-end" id="pills-tab" role="tablist">
          <li class="nav-item" role="presentation">
            <button class="nav-link active" id="pills-all-tab" data-bs-toggle="pill" data-bs-target="#pills-all" type="button" role="tab" aria-controls="pills-all" aria-selected="true">All</button>
          </li>
          <li class="nav-item" role="presentation">
            <button class="nav-link" id="pills-unread-tab" data-bs-toggle="pill" data-bs-target="#pills-unread" type="button" role="tab" aria-controls="pills-unread" aria-selected="false">Unread</button>
          </li>
        </ul>
    </div>
    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-all" role="tabpanel" aria-labelledby="pills-all-tab" tabindex="0">
        <div class="list-group">
            <a href="{% url "notifications:read_all" %}">Mark all read</a>
            {% for obj in notifications %}
            {% if obj.is_read %}
            <a href="{{ obj.url }}" class="list-group-item list-group-item-action" aria-current="true">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1">{{ obj.title }}</h5>
                  <small>{{ obj.created_at.date }}</small>
                </div>
                <p class="mb-1">{{ obj.message }}.</p>
            </a>
            {% else %}
            <a href="{{ obj.url }}" class="list-group-item list-group-item-action active" aria-current="true">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1">{{ obj.title }}</h5>
                  <small>{{ obj.created_at.date }}</small>
                </div>
                <p class="mb-1">{{ obj.message }}.</p>
            </a>
            {% endif %}
            {% endfor %}
        </div>
      </div>
      <div class="tab-pane fade" id="pills-unread" role="tabpanel" aria-labelledby="pills-unread-tab" tabindex="0">
        <div class="list-group">
            <a href="{% url "notifications:read_all" %}">Mark all read</a>
            {% for obj in notifications %}
            <a href="{{ obj.url }}" class="list-group-item list-group-item-action active" aria-current="true">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1">{{ obj.title }}</h5>
                  <small>{{ obj.created_at.date }}</small>
                </div>
                <p class="mb-1">{{ obj.message }}.</p>
            </a>
            {% endfor %}
        </div>
      </div>
    </div>
    
    {% if notifications %}
        {% with notifications as page_obj %}
            {% include "partials/_pagination.html" %}
        {% endwith %}
    {% endif %}
</div>
{% endblock %}