pkg/apps/home/urls.py
from django.urls import path 
from . import views

app_name = "home"

urlpatterns = [
    path("", views.LandingView.as_view(), name="landing_page"),
    path("contact-us/", views.contact_us, name="contact-us"),
]

pkg/apps/users/urls.py
from django.urls import path, re_path, include

from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("profile/", views.UserProfileView.as_view(), name="profile"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("activation/<user>/<token>/", views.account_confirmation, name="activation"),
    path("password-reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path("password-reset/<user>/<token>/", views.password_reset_confirm, name="password_reset_confirm"),
    
    ## OTP URLS
    path("generate-otp/", views.GenerateOTP.as_view(), name="generate_OTP"),
    path("validate-otp/", views.ValidateOTP.as_view(), name="validate_OTP"),
    path("disable-otp/", views.disableOTP, name="disable_OTP"),
]

pkg/apps/users/models.py
import hashid_field
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.models import BaseUserManager
from django.contrib.auth.models import Group
from django.db import models

from datetime import date

from common.acl.helpers import CommonGroups
from common.models import ImageWithThumbnailMixin
from common.storages import UniqueFilePathGenerator, PublicS3Boto3StorageWithCDN

# from . import notifications

from djstripe import models as djstripe_models


class UserManager(BaseUserManager):
    def get_queryset(self):
        return super().get_queryset().prefetch_related("notifications").all()
    
    def create_user(self, email, password=None):
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email).lower(),
        )
        user.set_password(password)
        group_user, _ = Group.objects.get_or_create(name=CommonGroups.User)
        user.save(using=self._db)
        user.groups.add(group_user)
        UserProfile.objects.create(user=user)

        return user

    def create_superuser(self, email, password):
        user = self.create_user(
            email,
            password=password,
        )
        group_admin, _ = Group.objects.get_or_create(name=CommonGroups.Admin)
        user.is_active = True
        user.is_superuser = True
        user.groups.add(group_admin)
        user.save(using=self._db)
        return user

    def filter_admins(self):
        return self.filter(groups__name=CommonGroups.Admin)


class User(AbstractBaseUser, PermissionsMixin):
    id = hashid_field.HashidAutoField(primary_key=True)
    created = models.DateTimeField(editable=False, auto_now_add=True)
    email = models.EmailField(
        verbose_name="email address",
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    
    paid_until = models.DateField(null=True)
    
    otp_enabled = models.BooleanField(default=False)
    otp_verified = models.BooleanField(default=False)
    otp_base32 = models.CharField(max_length=255, blank=True, default='')
    otp_auth_url = models.CharField(max_length=255, blank=True, default='')

    objects = UserManager()

    USERNAME_FIELD = "email"

    def __str__(self) -> str:
        return self.email

    @property
    def is_staff(self):
        return self.is_superuser

    def has_group(self, name):
        return self.groups.filter(name=name).exists()
    
    @property
    def get_roles(self):
        from .services.users import get_role_names
        return get_role_names(self)
    
    @property
    def has_unread_notifications(self):
        from apps.notifications.services import NotificationService
        return NotificationService.user_has_unread_notifications(self)
    
    def set_paid_until(self, date_or_timestamp):
        if isinstance(date_or_timestamp, int):
            paid_until = date.fromtimestamp(date_or_timestamp)
        elif isinstance(date_or_timestamp, str):
            paid_until = date.fromtimestamp(int(date_or_timestamp))
        else:
            paid_until = date_or_timestamp
        
        self.paid_until = paid_until
        self.save()
    
    @property
    def customer(self):
        customer = djstripe_models.Customer.objects.filter(subscriber=self)
        if customer.exists():
            return customer.first()
        # customer.active_subscriptions
        # customer.subscriptions
        # customer.has_any_active_subscription()
        # customer.valid_subscriptions
        # customer.is_subscribed_to(product)
        return None
    
    @property
    def is_subscribed(self):
        return self.customer.has_any_active_subscription()


class UserAvatar(ImageWithThumbnailMixin, models.Model):
    original = models.ImageField(
        storage=PublicS3Boto3StorageWithCDN, upload_to=UniqueFilePathGenerator("avatars"), null=True
    )
    thumbnail = models.ImageField(
        storage=PublicS3Boto3StorageWithCDN, upload_to=UniqueFilePathGenerator("avatars/thumbnails"), null=True
    )

    THUMBNAIL_SIZE = (128, 128)
    ERROR_FIELD_NAME = "avatar"

    def __str__(self) -> str:
        return str(self.id)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    first_name = models.CharField(max_length=40, blank=True, default='')
    last_name = models.CharField(max_length=40, blank=True, default='')
    avatar = models.OneToOneField(
        UserAvatar, 
        on_delete=models.SET_NULL, 
        null=True, blank=True, 
        related_name="user_profile"
    )

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"
    
    @property
    def email(self):
        """Get the profile user email
        
        This is needed by dj-stripe
        """
        return self.user.email

pkg/apps/users/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView
from django.views.generic import View
from django.utils.decorators import method_decorator

from allauth.decorators import rate_limit
from allauth.core import ratelimit

import qrcode

from . import forms, models, tokens, jwt, decorators, utils
from .services import otp as otp_services


# Create your views here.
@method_decorator(decorators.authentication_not_required, name="dispatch")
@method_decorator(rate_limit(action="login"), name="dispatch")
class LoginView(FormView):
    form_class = forms.UserLoginForm
    template_name = "users/login.html" 
    success_url = reverse_lazy("users:profile")
    
    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
        
    def form_valid(self, form):
        password = form.cleaned_data["password"]
        email = form.cleaned_data["email"]
        
        user = authenticate(username=email, password=password)
        
        if user is not None:
            if user.is_active:
                if user.otp_enabled and user.otp_verified:
                    context = {
                        "form": forms.ValidateOTPForm(initial={"user_id": user.id})
                    }
                    return render(request, "users/validate_otp.html", context)
                else:
                    login(self.request, user)
                    messages.success(self.request, "Login successful!")
            else:
                messages.info(self.request, "Check your emaill to activate your account!")
        else:
            messages.error(self.request, "Invalid credentials")
        return super().form_valid(form)


class LogoutView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return render(request, "users/login.html")


class UserProfileView(LoginRequiredMixin, View):
    
    def get(self, request, *args, **kwargs):
        profile = models.UserProfile.objects.prefetch_related("user", "avatar").get(user=request.user)
        profile_data = {
            "first_name": profile.first_name,
            "last_name": profile.last_name,
            # "email": request.user.email,
            "avatar": profile.avatar,
        }
        context = {
            "profile": profile, 
            "profile_form": forms.UserProfileForm(initial=profile_data),
            "password_change_form": forms.UserAccountChangePasswordForm(request.user),
        }
        if settings.SUBSCRIPTION_ENABLE:
            context["subscription"] = True
        else:
            context["subscription"] = False
        return render(request, "users/profile.html", context)
    
    def post(self, request, *args, **kwargs):
        profile = models.UserProfile.objects.prefetch_related("user", "avatar").get(user=request.user)
        profile_data = {
            "first_name": profile.first_name,
            "last_name": profile.last_name,
            # "email": request.user.email,
            "avatar": profile.avatar,
        }
        
        update_form = forms.UserProfileForm(request.POST, initial=profile_data)
        if update_form.has_changed():
            if update_form.is_valid():
                avatar = update_form.cleaned_data.get("avatar", None)
                if avatar:
                    update_form.validate_avatar(avatar)
                update_form.update(profile)
                messages.success(request, "Profile update successful!")
            else:
                for error in update_form.errors.values():
                    messages.error(request, error)
        
        context = {
            "profile": profile, 
            "profile_form": update_form,
            "password_change_form": forms.UserAccountChangePasswordForm(request.user),
        }
        
        if request.POST.get("new_password1"):
            password_change_form = forms.UserAccountChangePasswordForm(user=request.user, data=request.POST)
            if password_change_form.is_valid():
                password_change_form.save()
                utils.logout_on_password_change(request, request.user)
                messages.success(request, "Password change successful!")
            else:
                for error in password_change_form.errors.values():
                    messages.error(request, error)
            context["password_change_form"] = password_change_form
        return render(request, "users/profile.html", context)


@method_decorator(decorators.authentication_not_required, name="dispatch")
@method_decorator(rate_limit(action="signup"), name="dispatch")
class SignUpView(FormView):
    form_class = forms.UserSignupForm
    template_name = "users/signup.html" 
    success_url = reverse_lazy("users:login")
    
    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            return self.form_valid(form)
        else:
            for error in form.errors.values():
                messages.error(request, error) 
            return self.form_invalid(form)
        
    def form_valid(self, form):
        form.save()
        messages.info(self.request, "Confirm your email to activate your account")
        return super().form_valid(form)


def account_confirmation(request, user, token):
    form = forms.UserAccountConfirmationForm(data={"user": user, "token": token})
    if form.is_valid():
        form.save()
        messages.success(request, "Account verification successful!")
        return redirect(reverse('users:profile'))
    for error in form.errors.values():
        messages.error(request, error)
    return redirect(reverse('users:login'))


@method_decorator(rate_limit(action="reset_password"), name="dispatch")
@method_decorator(decorators.authentication_not_required, name="dispatch")
class PasswordResetView(FormView):
    form_class = forms.PasswordResetForm
    template_name = "users/password_reset.html" 
    success_url = reverse_lazy("users:login") 
    
    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            return self.form_valid(form)
        else:
            for error in form.errors.values():
                messages.error(request, error) 
            return self.form_invalid(form)
    
    def form_valid(self, form):
        r429 = ratelimit.consume_or_429(
            self.request,
            action="reset_password_email",
            key=form.cleaned_data["email"].lower(),
        )
        if r429:
            return r429
        form.save()
        messages.info(self.request, "Email has been sent your email with instructions to reset your password")
        return super(PasswordResetView, self).form_valid(form)


def password_reset_confirm(request, user, token):
    user = get_object_or_404(models.User, id=user)
    
    if not tokens.password_reset_token.check_token(user, token):
        messages.error(request, "Malformed password reset token")
        return redirect("users:password_reset")
    if request.method == "POST":
        form = forms.PasswordResetConfirmationForm(user, request.POST)
        if form.is_valid():
            form.save()
            jwt.blacklist_user_tokens(user)
            messages.success(request, "Password reset successful!")
            return redirect("users:login")
        for error in form.errors.values():
            messages.error(request, error)
    form = forms.PasswordResetConfirmationForm(user)
    return render(request, "users/password_reset_confirm.html", {"form": form})


def get_qrcode_path(hashid):
    path = settings.BASE_DIR / "static" / "img" / "qrcode" / f"{hashid}.png"
    return path, f"img/qrcode/{hashid}.png"


class GenerateOTP(LoginRequiredMixin, FormView):
    """
    Enabling two-factor authentication with authentication app
    """
    
    form_class = forms.VerifyOTPForm
    template_name = "users/generate_otp.html" 
    success_url = reverse_lazy("users:profile") 
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        
        otp_base32, otp_auth_url = otp_services.generate_otp(self.request.user)
        qrcode_img_path, img_name = get_qrcode_path(self.request.user.id.hashid)
        print(otp_auth_url)
        qrcode.make(otp_auth_url).save(qrcode_img_path)
        
        context["img_name"] = img_name
        context["otp_auth_url"] = otp_auth_url
        return context
    
    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            return self.form_valid(form)
        else:
            for error in form.errors.values():
                messages.error(request, error)
            return self.form_invalid(form)
        
    def form_valid(self, form):
        return super().form_valid(form)


class ValidateOTP(FormView):
    """
        2FA Authentication 
    """
    
    form_class = forms.ValidateOTPForm
    template_name = "users/validate_otp.html" 
    success_url = reverse_lazy("users:profile") 
    
    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)

pkg/apps/users/templates/users/confirmation_resend.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="m-auto">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                
                <div class="h2 text-center my-4">Resend account confirmation</div>
                
                <form action="." method="post" class="form-group">
                    {% csrf_token %}
                    
                    <p>Write down your email and we will send you link to confirm your account</p>
                    
                    {% for field in form %}
                        {% include "users/partials/_field.html" %}
                    {% endfor %}
                    
                    <div class="d-grid mb-4">
                      <input type="submit" class="btn btn-dark" value="Send the link"  >
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

pkg/apps/users/templates/users/generate_otp.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="m-auto">
    <div class="container">
        <div class="row">
            <div class="col">
                
                <div class="h2 text-center my-4">Enable two-factor Authentication</div>
                
                <div class="mb-3 text-center d-flex flex-column justify-content-center">
                    <div class="mb-3">
                        <div>
                            <img src="{% static img_name %}" class="object-fit-fill border rounded" alt="qrcode-image">
                        </div>
                        <p class="text-muted">Scan the QRcode with an authentication app</p>
                    </div>
                    <div class="mb-3">or</div>
                    <div class="mb-3">
                        <code>
                            {{ otp_auth_url }}
                        </code>
                        <p class="text-muted">Enter the url in an authentication app</p>
                    </div>
                </div>
                
                
                <form action="." method="post" class="form-group">
                    {% csrf_token %}
                    
                    <p class="text-center">Enter the OTP provided by the authentication app</p>
                    
                    {% for field in form %}
                        {% include "users/partials/_field.html" %}
                    {% endfor %}
                    
                    <div class="d-grid mb-4">
                      <input type="submit" class="btn btn-dark" value="Submit OTP"  >
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

pkg/apps/users/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load socialaccount %}

{% block content %}
<div class="m-auto">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                
                <div class="h2 text-center my-4">Log In</div>
                
                <div class="my-2">
                    {% if next %}
                        {% if user.is_authenticated %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                          To proceed, please login with an account that has access.
                          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                        {% else %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                          Please login to proceed
                          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                        {% endif %}
                    {% endif %}
                </div>
                
                <div class="d-grid gap-2">
                    <a href="{% provider_login_url "facebook" method="oauth2" %}" class="btn btn-light"><span class="px-2"><i class="bi bi-facebook"></i></span>Login with Facebook</a>
                    <a href="{% provider_login_url "google" method="oauth2" %}" class="btn btn-light"><span class="px-2"><i class="bi bi-google"></i></span>Login with Google</a>
                </div>
                <h5 class="text-center mt-3">or</h5>
                <form action="." method="post" class="form-group">
                    {% csrf_token %}
                    
                    {% for field in form %}
                        {% include "users/partials/_field.html" %}
                    {% endfor %}
                    
                    <div class="d-grid mb-3">
                      <input type="submit" class="btn btn-dark" value="Login"  >
                      <input type="hidden" name="next" value="{{ next }}">
                    </div>
                    <div class="d-flex justify-content-between">
                        <a href="{% url "users:password_reset" %}">Forgot Password?</a>
                        <a href="{% url "users:signup" %}">Sign Up</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

pkg/apps/users/templates/users/password_reset.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="m-auto">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                
                <div class="h2 text-center my-4">Forgot password?</div>
                
                <form action="." method="post" class="form-group">
                    {% csrf_token %}
                    
                    <p>Write down your email and we will send you link to reset your password</p>
                    
                    {% for field in form %}
                        {% include "users/partials/_field.html" %}
                    {% endfor %}
                    
                    <div class="d-grid mb-4">
                      <input type="submit" class="btn btn-dark" value="Send the link"  >
                    </div>
                    <div class="d-flex justify-content-center">
                        <a class="text-decoration-none" href="{% url "users:login" %}">Go back to login</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

pkg/apps/users/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="m-auto">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                
                <div class="h2 text-center my-4">Password Reset</div>
                
                <form action="." method="post" class="form-group">
                    {% csrf_token %}
                    
                    <p>Enter new password to reset your account password</p>
                    
                    {% for field in form %}
                        {% include "users/partials/_field.html" %}
                    {% endfor %}
                    
                    <div class="d-grid mb-4">
                      <input type="submit" class="btn btn-dark" value="Set new password"  >
                    </div>
                    <div class="d-flex justify-content-center">
                        <a class="text-decoration-none" href="{% url "users:login" %}">Go back to login</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

pkg/apps/users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="container">
    <div class="my-4">
        <div id="user-info" class="mb-4">
            <div class="row">
                <div class="col-3">
                    <img src="{{ user.avatar.url }}" class="img-thumbnail" alt="{{ profile }}">
                </div>
                <div class="col-9">
                    <p><span class="fw-bold">Name:</span> {{ profile }}</p>
                    <p><span class="fw-bold">Email:</span> {{ user.email }}</p>
                    <p><span class="fw-bold">Roles:</span> {{ user.get_roles }}</p>
                </div>
            </div>
            <a href="{% url 'finances:profile_subscription' %}" class="btn btn-dark">Subscription</a>
        </div>
        <div id="user-profile" class="mb-4">
            <h4>Personal data</h4>
            <p class="text-muted">Update your account details</p>
            <hr>
            <form action="." class="form-group" method="post">
                {% csrf_token %}
                <div class="row">
                    {% for field in profile_form %}
                    <div class="col-6">
                        {% include "users/partials/_field.html" %}
                    </div>
                    {% endfor %}
                </div>
                <div class="mb-4">
                  <input type="submit" class="btn btn-dark" value="Update personal data"  >
                </div>
            </form>
        </div>
        <div id="user-password-change" class="mb-4">
            <h4>Change Password</h4>
            <p class="text-muted">Update your password</p>
            <hr>
            <form action="." class="form-group" method="post">
                {% csrf_token %}
                <div class="row">
                    {% for field in password_change_form %}
                    <div class="col-6">
                        {% include "users/partials/_field.html" %}
                    </div>
                    {% endfor %}
                </div>
                <div class="mb-4">
                  <input type="submit" class="btn btn-dark" value="Change password"  >
                </div>
            </form>
        </div>
        <div id="user-2FA" class="mb-4">
            <h4>Two-factor Authentication</h4>
            <p class="text-muted">Enable 2FA on your account</p>
            <hr>
            {% if user.otp_enabled %}
            <p>Your account is using two-factor authentication</p>
            <a href="{% url "users:disable_OTP" %}" class="btn btn-dark">Disable 2FA</a>
            {% else %}
            <p>Your account is not using two-factor authentication</p>
            <a href="{% url "users:generate_OTP" %}" class="btn btn-dark">Setup 2FA</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

pkg/apps/users/templates/users/signup.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load socialaccount %}

{% block content %}
<div class="m-auto">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                
                <div class="h2 text-center my-4">Sign Up</div>
                
                <div class="d-grid gap-2">
                    <a href="{% provider_login_url "facebook" method="oauth2" %}" class="btn btn-light"><span class="px-2"><i class="bi bi-facebook"></i></span>Sign up with Facebook</a>
                    <a href="{% provider_login_url "google" method="oauth2" %}" class="btn btn-light"><span class="px-2"><i class="bi bi-google"></i> </span>Sign up with Google</a>
                </div>
                <h5 class="text-center mt-3">or</h5>
                <form action="." method="POST" class="form-group">
                    {% csrf_token %}
                    
                    {% for field in form %}
                        {% include "users/partials/_field.html" %}
                    {% endfor %}
                    
                    <div class="form-check mb-3">
                      <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                      <label class="form-check-label" for="flexCheckDefault">
                        You must accept our Terms of Use and Privacy Policy 
                      </label>
                    </div>
                    
                    <div class="d-grid mb-4">
                      <input type="submit" class="btn btn-dark" value="Sign up"  >
                    </div>
                    <div class="d-flex justify-content-center">
                        <a class="text-decoration-none" href="{% url "users:login" %}">Login</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

pkg/apps/users/templates/users/validate_otp.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="m-auto">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                
                <div class="h2 text-center my-4">2FA Authentication</div>
                
                <form action="{% url 'users:validate_OTP' %}" method="post" class="form-group">
                    {% csrf_token %}
                    
                    <p>Enter the OTP from the authentication app to login</p>
                    
                    {% for field in form %}
                        {% include "users/partials/_field.html" %}
                    {% endfor %}
                    
                    <div class="mb-4 text-center">
                      <input type="submit" class="btn btn-dark btn-lg" value="Validate login"  >
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}